import { supabase } from '../../supabase'

type StoreSlug = 'hobby-games'

type Game = {
  id: number
  titleRu: string | null
  titleEn: string | null
  playtimeMin: number
  playtimeMax: number | null
  playersMin: number
  playersMax: number | null
  images: string[]
  stores: { storeSlug: StoreSlug; url: string; price: number }[]
}

// const games: Game[] = [
//   // {
//   //   titleRu: 'Фиеста',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/fiesta-karnaval-mjortvih', price: 2590 }],
//   //   playtimeMax: null,
//   //   playtimeMin: 15,
//   //   playersMin: 4,
//   //   playersMax: 8,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Style_Jizny/Fiesta/Fiesta-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Fiesta',
//   // },
//   // {
//   //   titleRu: 'Серп',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/serp', price: 6990 }],
//   //   playtimeMax: 115,
//   //   playtimeMin: 115,
//   //   playersMin: 1,
//   //   playersMax: 5,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/CrowD_Games/Scythe/scythe_box-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Serp',
//   // },
//   // {
//   //   titleRu: 'Покорение Марса',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/pokorenie-marsa', price: 4490 }],
//   //   playtimeMax: 120,
//   //   playtimeMin: 180,
//   //   playersMin: 1,
//   //   playersMax: 5,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Proekt_Venera/Pokorenie_Marsa-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Terraforming Mars',
//   // },
//   // {
//   //   titleRu: 'Забытые моря',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/zabitie-morja', price: 4490 }],
//   //   playtimeMax: 120,
//   //   playtimeMin: 240,
//   //   playersMin: 3,
//   //   playersMax: 7,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/CrowD_Games/Zabytye_morya/Photos/Zabitie_Morya-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Лаборатория',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/laboratoriya-2.0', price: 3790 }],
//   //   playtimeMax: 30,
//   //   playtimeMin: 45,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Interhit/Laboratoria/2.0/HG/Laboratoria-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Цолькин',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/colkin-kalendar-majja', price: 4290 }],
//   //   playtimeMax: null,
//   //   playtimeMin: 90,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: ['https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Gaga/Tzolkin/Tzolkin-1024x1024-wm.jpg'],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Чемпионы Мидгарда',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/chempioni-midgarda', price: 3750 }],
//   //   playtimeMax: 60,
//   //   playtimeMin: 90,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Chempioni_Midgarda/Chempioni_Midgarda-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Последний Бастион',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/last-bastion', price: 6750 }],
//   //   playtimeMax: null,
//   //   playtimeMin: 45,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Style_Jizny/Last_bastion/HG/Last_Bastion-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Last Bastion',
//   // },
//   // {
//   //   titleRu: 'Остров Кошек',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/ostrov-koshek', price: 5_290 }],
//   //   playtimeMax: 90,
//   //   playtimeMin: 60,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Gaga/Ostrov_Koshek/HG/Ostrov_Koshek-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Крылья',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/krilja', price: 4750 }],
//   //   playtimeMax: 70,
//   //   playtimeMin: 40,
//   //   playersMin: 1,
//   //   playersMax: 5,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Krylya/Krilya-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Wingspan',
//   // },
//   // {
//   //   titleRu: 'Чёрный ангел',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/chernij-angel', price: 5490 }],
//   //   playtimeMax: 60,
//   //   playtimeMin: 120,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/CrowD_Games/Black_Angel/Cherniy_Angel-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Архитекторы западного королевства',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/arhitektori-zapadnogo-korolevstva', price: 2990 }],
//   //   playtimeMax: 60,
//   //   playtimeMin: 80,
//   //   playersMin: 1,
//   //   playersMax: 5,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Arhitektory/Architektory-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Алхимики',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/alhimiki', price: 4490 }],
//   //   playtimeMax: null,
//   //   playtimeMin: 120,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Gaga/Alchimiki/HG/Alhimiki-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Эверделл',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/jeverdell', price: 5990 }],
//   //   playtimeMax: 40,
//   //   playtimeMin: 80,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/HobbyWorld/Everdell/Ehverdell00-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: 'Everdell',
//   // },
//   // {
//   //   titleRu: 'Саграда',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/sagrada', price: 2750 }],
//   //   playtimeMax: 30,
//   //   playtimeMin: 45,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/CrowD_Games/Sagrada/Photos/Sagrada_01-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleEn: 'Runebound',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/runebound-tretja-redakcija', price: 4990 }],
//   //   playtimeMax: 120,
//   //   playtimeMin: 180,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/HobbyWorld/Runebound_3ed/Runebound_3ed_3D_roznica-1024x1024-wm.jpg',
//   //   ],
//   //   titleRu: null,
//   // },
//   // {
//   //   titleRu: 'Кланк!',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/klank-podzemnoe-prikljuchenie', price: 3990 }],
//   //   playtimeMax: 60,
//   //   playtimeMin: 30,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Clank/Klank-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleRu: 'Селестия',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/selestija', price: 2790 }],
//   //   playtimeMax: null,
//   //   playtimeMin: 30,
//   //   playersMin: 2,
//   //   playersMax: 6,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Evrikus/Selestia/Selestia-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   // {
//   //   titleEn: 'Rise of Tribes',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/plemena', price: 4990 }],
//   //   playtimeMax: 60,
//   //   playtimeMin: 30,
//   //   playersMin: 2,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Magellan/Plemena/plemena_00-1024x1024-wm.jpg',
//   //   ],
//   //   titleRu: 'Племена',
//   // },
//   // {
//   //   titleRu: 'Теотиуакан',
//   //   stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/teotiuakan-gorod-bogov', price: 4290 }],
//   //   playtimeMax: 120,
//   //   playtimeMin: 90,
//   //   playersMin: 1,
//   //   playersMax: 4,
//   //   images: [
//   //     'https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/CrowD_Games/Teotiuakan/HG/Teotiuakan-1024x1024-wm.jpg',
//   //   ],
//   //   titleEn: null,
//   // },
//   {
//     titleEn: 'Mission Red Planet',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/mission-red-planet' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleRu: 'Королевство кроликов',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/korolevstvo-krolikov' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleEn: 'Keyflower',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/keyflower' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleRu: 'Древний ужас',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/drevnij-uzhas' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Сумерки империи',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/sumerki-imperii-chetvjortoe-izdanie' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Визуал',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/vizual' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Сквозь века',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/skvoz-veka-novaja-istorija-civilizacii' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Палео',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/paleo' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Робинзон Крузо',
//     stores: [
//       {
//         storeSlug: 'hobby-games',
//         url: 'https://hobbygames.ru/robinzon-kruzo-prikljuchenija-na-tainstvennom-ostrove-vtoraja-redakcija',
//       },
//     ],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Плотина',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/plotina' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Энергосеть',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/jenergoset-novaja-redakcija' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Остров духов',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/ostrov-duhov' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Этнос',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/jetnos' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleEn: 'Cosmic Encounter',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/kosmicheskij-kontakt' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleRu: 'Киклады',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/kikladi' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Кровь и ярость',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/blood-rage' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Маленький мир',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/small-world' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Звездные империи',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/komnata-25-plan-pobega' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Немезида',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/nemezida' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleEn: 'Five Tribes',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/pjat-plemjon-dzhinni-nakali' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleEn: 'Root',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/root' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleRu: 'Колонизаторы',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/catan-jubilejnoe-izdanie' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Особняки безумия',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/osobnjaki-bezumija-vtoraja-redakcija' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleEn: 'Inis',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/inish' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleEn: 'Mr. Jack',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/mr-jack' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleRu: null,
//   },
//   {
//     titleRu: 'Кольт Экспресс',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/kolt-jekspress' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Оскверненный Грааль',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/oskvernjonnij-graal-padenie-avalona' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Восход 5',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/voshod-5-runi-asterosa' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
//   {
//     titleRu: 'Подводные города',
//     stores: [{ storeSlug: 'hobby-games', url: 'https://hobbygames.ru/podvodnie-goroda' }],
//     playtimeMax: 0,
//     playtimeMin: 0,
//     playersMin: 0,
//     playersMax: 0,
//     images: [],
//     titleEn: null,
//   },
// ]

export default defineEventHandler(async () => {
  const { data: games } = await supabase.from<Game>('games').select('*')

  // await supabase.from<Game>('games').insert(games)

  return { games: games ?? [] }
})
